using System.Text;
using System.Text.RegularExpressions;

namespace DungeonsOfSkaraBrae.Ink;

public sealed record KnotManifestEntry(string KnotName, string FilePath);

public sealed class AssemblyResult
{
    public required string MainInkPath { get; init; }
    public required IReadOnlyList<KnotManifestEntry> Knots { get; init; }
    public required IReadOnlyList<string> Warnings { get; init; }
}

public static partial class Assembler
{
    [GeneratedRegex(@"^\s*={2,}\s*(\w+)\s*={0,}\s*$", RegexOptions.Multiline)]
    private static partial Regex KnotRegex();

    public static AssemblyResult Assemble(string storyRoot)
    {
        var buildDir = Path.Combine(storyRoot, ".build");
        Directory.CreateDirectory(buildDir);

        var knotsDir = Path.Combine(storyRoot, "knots");
        var globalsPath = Path.Combine(storyRoot, "globals.ink");
        var mainPath = Path.Combine(buildDir, "main.ink");

        var warnings = new List<string>();
        var knots = new List<KnotManifestEntry>();

        if (Directory.Exists(knotsDir))
        {
            foreach (var file in Directory.EnumerateFiles(knotsDir, "*.ink", SearchOption.AllDirectories))
            {
                var rel = Path.GetRelativePath(storyRoot, file).Replace('\\', '/');
                var content = File.ReadAllText(file);
                var matches = KnotRegex().Matches(content);
                if (matches.Count == 0)
                {
                    warnings.Add($"{rel}: no `=== knot_name ===` declaration found, skipping.");
                    continue;
                }

                foreach (Match m in matches)
                {
                    knots.Add(new KnotManifestEntry(m.Groups[1].Value, file));
                }

                var primary = matches[0].Groups[1].Value;
                var fileBase = Path.GetFileNameWithoutExtension(file);
                if (!string.Equals(primary, fileBase, StringComparison.Ordinal))
                {
                    warnings.Add($"{rel}: primary knot `{primary}` does not match filename `{fileBase}`.");
                }
            }
        }

        foreach (var dup in knots.GroupBy(k => k.KnotName).Where(g => g.Count() > 1))
        {
            var files = string.Join(", ", dup.Select(k => Path.GetRelativePath(storyRoot, k.FilePath).Replace('\\', '/')));
            warnings.Add($"Knot `{dup.Key}` is declared in multiple files: {files}");
        }

        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by DungeonsOfSkaraBrae assembler. Do not edit.");
        if (File.Exists(globalsPath))
        {
            sb.AppendLine($"INCLUDE {RelFromBuild(globalsPath, buildDir)}");
        }
        foreach (var file in knots.Select(k => k.FilePath)
                                  .Distinct(StringComparer.OrdinalIgnoreCase)
                                  .OrderBy(p => p, StringComparer.Ordinal))
        {
            sb.AppendLine($"INCLUDE {RelFromBuild(file, buildDir)}");
        }
        sb.AppendLine();
        sb.AppendLine("-> start");

        File.WriteAllText(mainPath, sb.ToString());

        return new AssemblyResult
        {
            MainInkPath = mainPath,
            Knots = knots,
            Warnings = warnings,
        };
    }

    private static string RelFromBuild(string target, string buildDir)
        => Path.GetRelativePath(buildDir, target).Replace('\\', '/');
}
